[build]
  command = "npm install && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  VITE_SOME_KEY = "production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
